modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Crendgrim/AutoHUD/issues"
license = "LGPL-3.0"

[[mods]]
modId = "autohud"
version = "${version}"
displayName = "Auto HUD"
authors = "Crendgrim"
description = '''
 Dynamic HUD that hides interface elements while they are not needed.
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.autohud]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autohud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autohud]]
modId = "yet_another_config_lib"
mandatory = false
versionRange = "[2.5,)"
ordering = "NONE"
side = "BOTH"